server:
  port: ${SERVER_PORT:5001}

#Datasource Configuration
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/tutuka?createDatabaseIfNotExist=true
    username: 'developer'
    password: 'tutuka125'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  output:
    ansi:
      enabled: always

#Logging Configuration
logging:
  level:
    ROOT: info
    org.hibernate: error
    com.zaxxer.hikari.pool: error
    org.springframework.web: info
    org.springframework.web.filter.CommonsRequestLoggingFilter: debug
    com.tutuka: info
  file: '/data/tutuka/transaction-comparator.log'


#Temporary Directory to upload the files
com:
  tutuka:
    fileDirectory: '/tmp'
